name: mini_deha
description: "A secure and educational app for children."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.0.5
  # Firebase dependencies
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  # Video Player (YouTube)
  youtube_player_flutter: ^9.0.1
  # In-app purchase for Freemium model
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets will be added here
  # assets:
  #   - assets/images/
